/**
 * Frozen legacy IPC channel allowlists (ADR-003 first-stage lockdown).
 *
 * These are the ONLY channels the generic `window.api.ipc.send/invoke/on`
 * bridge accepts. The set must never grow: new capabilities get narrow,
 * schema-validated methods (see src/common/contracts) — not new entries
 * here. test/unit/specs/ipc-channel-freeze.spec.js pins the exact
 * contents; shrinking the lists as capabilities migrate is the goal.
 */

export const LEGACY_SEND_CHANNELS = Object.freeze([
  'mt::INSTALL_UPDATE_NOW',
  'mt::NEED_UPDATE',
  'mt::app-try-quit',
  'mt::ask-for-modify-image-folder-path',
  'mt::ask-for-open-project-in-sidebar',
  'mt::ask-for-user-data',
  'mt::ask-for-user-preference',
  'mt::check-for-update',
  'mt::clear-recently-used-documents',
  'mt::close-window',
  'mt::close-window-confirm',
  'mt::cmd-close-window',
  'mt::cmd-import-file',
  'mt::cmd-new-editor-window',
  'mt::cmd-open-file',
  'mt::cmd-open-folder',
  'mt::cmd-toggle-autosave',
  'mt::editor-selection-changed',
  'mt::format-link-click',
  'mt::handle-renderer-error',
  'mt::keybinding-debug-dump-keyboard-info',
  'mt::make-screenshot',
  'mt::open-file',
  'mt::open-file-by-window-id',
  'mt::open-file-or-folder',
  'mt::open-keybindings-config',
  'mt::open-setting-window',
  'mt::rename',
  'mt::request-keybindings',
  'mt::response-export',
  'mt::response-file-move-to',
  'mt::response-file-save',
  'mt::response-file-save-as',
  'mt::response-print',
  'mt::save-and-close-tabs',
  'mt::save-tabs',
  'mt::select-default-directory-to-open',
  'mt::set-user-data',
  'mt::set-user-preference',
  'mt::show-app-menu',
  'mt::sidebar-context-menu',
  'mt::tab-context-menu',
  'mt::update-format-menu',
  'mt::update-line-ending-menu',
  'mt::update-sidebar-menu',
  'mt::view-layout-changed',
  'mt::window-add-file-path',
  'mt::window-document-state',
  'mt::window-tab-closed',
  'mt::window-toggle-always-on-top',
] as const)

export const LEGACY_RECEIVE_CHANNELS = Object.freeze([
  'mt::UPDATE_AVAILABLE',
  'mt::UPDATE_DOWNLOADED',
  'mt::UPDATE_ERROR',
  'mt::UPDATE_NOT_AVAILABLE',
  'mt::about-dialog',
  'mt::ask-for-close',
  'mt::bootstrap-editor',
  'mt::cm-copy-as-html',
  'mt::cm-copy-as-markdown',
  'mt::cm-insert-paragraph',
  'mt::cm-paste-as-plain-text',
  'mt::editor-ask-file-save',
  'mt::editor-ask-file-save-as',
  'mt::editor-close-tab',
  'mt::editor-edit-action',
  'mt::editor-format-action',
  'mt::editor-move-file',
  'mt::editor-paragraph-action',
  'mt::editor-rename-file',
  'mt::execute-command-by-id',
  'mt::export-success',
  'mt::force-close-tabs-by-id',
  'mt::invalidate-image-cache',
  'mt::keybindings-response',
  'mt::new-untitled-tab',
  'mt::open-directory',
  'mt::open-new-tab',
  'mt::pandoc-not-exists',
  'mt::print-service-clearup',
  'mt::screenshot-captured',
  'mt::set-file-encoding',
  'mt::set-final-newline',
  'mt::set-line-ending',
  'mt::set-pathname',
  'mt::set-view-layout',
  'mt::show-command-palette',
  'mt::show-export-dialog',
  'mt::show-notification',
  'mt::sidebar-context-action',
  'mt::spelling-replace-misspelling',
  'mt::spelling-show-switch-language',
  'mt::switch-tab-by-index',
  'mt::tab-context-action',
  'mt::tab-save-failure',
  'mt::tab-saved',
  'mt::tabs-cycle-left',
  'mt::tabs-cycle-right',
  'mt::toggle-view-layout-entry',
  'mt::toggle-view-mode-entry',
  'mt::update-file',
  'mt::update-object-tree',
  'mt::user-preference',
  'mt::window-active-status',
  'mt::window-enter-full-screen',
  'mt::window-leave-full-screen',
  'mt::window-maximize',
  'mt::window-unmaximize',
  'mt::window-zoom',
  'settings::change-tab',
] as const)

export const LEGACY_INVOKE_CHANNELS = Object.freeze([
  'mt::ask-for-image-auto-path',
  'mt::ask-for-image-path',
  'mt::clipboard-get-files',
  'mt::clipboard-guess-file-path',
  'mt::clipboard-has-files',
  'mt::fs-trash-item',
  'mt::get-available-font-families',
  'mt::get-recently-used-documents',
  'mt::keybinding-get-keyboard-info',
  'mt::keybinding-get-pref-keybindings',
  'mt::keybinding-save-user-keybindings',
  'mt::spellchecker-get-available-dictionaries',
  'mt::spellchecker-get-custom-dictionary-words',
  'mt::spellchecker-remove-word',
  'mt::spellchecker-set-enabled',
  'mt::spellchecker-switch-language',
  'mt::window-is-fullscreen',
  'mt::window-is-maximized',
] as const)
